terraform {
  required_version = ">= 1.0"

  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

# ── Variables ──────────────────────────────────────────────────────────────────

variable "output_dir" {
  description = "Directory where generated files will be written."
  type        = string
  default     = "/tmp/forgeplane-test"
}

variable "environment" {
  description = "Deployment environment label (e.g. dev, staging, prod)."
  type        = string
  default     = "dev"
}

variable "app_name" {
  description = "Application name written into the generated config."
  type        = string
  default     = "forgeplane"
}

variable "replicas" {
  description = "Number of replicas to declare in the generated config."
  type        = number
  default     = 2
}

variable "generated_at" {
  description = "Stable generation timestamp written into deterministic test outputs."
  type        = string
  default     = "2026-01-01T00:00:00Z"
}

# ── Locals ─────────────────────────────────────────────────────────────────────

locals {
  config_content = jsonencode({
    app         = var.app_name
    environment = var.environment
    replicas    = var.replicas
    generated   = var.generated_at
  })

  readme_content = <<-EOT
    # ${var.app_name} — ${var.environment}

    Generated by Terraform at ${var.generated_at}.

    ## Config

    - **App**: ${var.app_name}
    - **Environment**: ${var.environment}
    - **Replicas**: ${var.replicas}
  EOT
}

# ── Resources ──────────────────────────────────────────────────────────────────

resource "local_file" "config" {
  filename        = "${var.output_dir}/config.json"
  content         = local.config_content
  file_permission = "0644"
}

resource "local_file" "readme" {
  filename        = "${var.output_dir}/README.md"
  content         = local.readme_content
  file_permission = "0644"
}

resource "local_sensitive_file" "secret" {
  filename        = "${var.output_dir}/secret.env"
  content         = "APP_SECRET=test-secret-${var.environment}\nAPP_ENV=${var.environment}\n"
  file_permission = "0600"
}

# ── Outputs ────────────────────────────────────────────────────────────────────

output "config_path" {
  description = "Path to the generated config file."
  value       = local_file.config.filename
}

output "readme_path" {
  description = "Path to the generated README file."
  value       = local_file.readme.filename
}

output "secret_path" {
  description = "Path to the generated secret env file."
  value       = local_sensitive_file.secret.filename
  sensitive   = true
}

output "config_summary" {
  description = "Summary of applied configuration."
  value = {
    app         = var.app_name
    environment = var.environment
    replicas    = var.replicas
    output_dir  = var.output_dir
  }
}
